#!/usr/bin/env bash

set -Eeuxo pipefail

if [[ -n $(git status --porcelain) ]]; then
  git config --global user.name "$GITHUB_ACTOR"
  git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
  git add -A
  git commit -m "Automated updates"
  set +x
  git remote set-url --push origin "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
  set -x
  git push origin HEAD:main
fi
