FROM mcr.microsoft.com/playwright:v1.10.0-focal

WORKDIR /app

COPY package.json yarn.lock /app/
ARG YARN_INSTALL_ARGS="--frozen-lockfile --production"
RUN set -x && yarn install $YARN_INSTALL_ARGS

COPY . /app

ENV NODE_OPTIONS="--unhandled-rejections=strict --trace-warnings"
ENV NODE_ENV=production
# ENV DEBUG=pw:api
