apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}-rite-aid-find-stores-cronjob
  labels:
    app: {{ .Chart.Name }}-rite-aid-find-stores
spec:
  schedule: "48 0 * * *"
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: {{ .Chart.Name }}-rite-aid-find-stores
          annotations:
            checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: {{ .Chart.Name }}-container-registry-secret
          containers:
            - name: {{ .Chart.Name }}-rite-aid-find-stores
              image: {{ index .Values.werf.image "vaccinespotter" }}
              args: ["bin/rite-aid-find-stores"]
              resources:
                requests:
                  memory: "128Mi"
              env:
                - name: LOG_LEVEL
                  value: notice
              envFrom:
                - secretRef:
                    name: {{ .Chart.Name }}-secrets
