apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-website-static-site-job-{{ .Release.Revision }}
spec:
  backoffLimit: 0
  template:
    metadata:
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      imagePullSecrets:
        - name: {{ .Chart.Name }}-container-registry-secret
      containers:
        - name: {{ .Chart.Name }}-website-static-site
          image: {{ index .Values.werf.image "vaccinespotter" }}
          args: ["bin/run", "website:static-site:build-and-publish"]
          env:
            - name: LOG_LEVEL
              value: notice
          envFrom:
            - secretRef:
                name: {{ .Chart.Name }}-secrets
