name: Shutdown Site

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish shutdown site to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.2
        with:
          source-directory: shutdown
          target-branch: gh-pages
